name: Run Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Lint and Test
    runs-on: ubuntu-latest

    env:
      VITE_CONVEX_URL: "http://localhost:1337/mock"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm ci

      - name: Run Linter
        run: npm run lint

      - name: Run Tests Coverage
        run: npm run test:coverage

      - name: Upload JUnit Test Report
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: junit-report
          path: test-report.junit.xml

      - name: Upload coverage reports to Codecov
        if: ${{ always() }}
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: plugveg/stock-merch-ugs

      - name: Upload test results to Codecov
        if: ${{ always() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
