name: Merge main into release

on:
  workflow_run:
    workflows: ["Test"]
    types:
      - completed

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: release
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Merge main into release
        run: |
          git fetch origin main
          git merge origin/main --no-edit
          git push origin release
